@hostname = localhost
@port = 4941
@host = {{hostname}}:{{port}}
@version = v1

###
# hello world
GET http://{{host}}/

###
# Force reset of database to original structure and reload sample of data into database.
POST http://{{host}}/api/{{version}}/reload

###
# Reload sample of data into database.
POST http://{{host}}/api/{{version}}/resample

###
# Force reset of database to original structure.
POST http://{{host}}/api/{{version}}/reset

###
# Execute any arbitrary SQL statement provided, and return the output from the database.
POST http://{{host}}/api/{{version}}/executeSql
Content-Type: text/plain

SELECT * FROM Category where category_id=1